apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#secretGenerator:
#  - name: switch-config
#    type: opaque
#    files:
#      - switches.yaml
resources:
  - deployment.yaml
  - service.yaml
